### ISSUE TITLE
wrong tags produced by `cases_core`

### ISSUE THREAD

**Issue by cipher1024** [leanprover-community/lean#388] opened 2020-07-09 01:37 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Some uses of `cases` followed by `case` cause `case` to fail to interpret the tags generated by `cases`.

### Steps to Reproduce

```lean
import logic.relation

open function relation

open tactic

def foo
  {α : Type}
  {r : α × α → Prop}
  {x : α × α}
  (h : uncurry (trans_gen (curry r)) x) :
  true :=
begin
  cases h,
  case relation.trans_gen.tail : a b c { admit }
end
```

**Expected behavior:** the proof of `foo` should be admitted

**Actual behavior:** `case` gives the following error message:

```
Cannot rename these hypotheses:
[anonymous]
This is because these hypotheses either do not occur in the
context or they occur before a frozen local instance.
In the latter case, try `tactic.unfreeze_local_instances`.
state:
case relation.trans_gen.tail
α : Type,
r : α × α → Prop,
x : α × α,
h_b : α,
h_a : trans_gen (curry r) x.fst h_b,
h_a_1 : curry r h_b x.snd
⊢ true
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

Lean (version 3.17.0, commit 5d8f59fd1d49, Release)
MacOS X 10.15.5 (19F101) 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/.60cases.60.20.2F.20.60case.20.7B.20.7D.60/near/203322131

**Comment by JLimperg** [comment] 2020-07-09 15:27
Duplicate of #345 I think.

**Closed** 2020-07-13 12:24 UTC
